name: flutter_import_sorter
description: Automatically organize your flutter imports
version: 0.0.1+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  args: ^2.4.2
  tint: ^2.0.1
  yaml: ^3.1.2

dev_dependencies:
  test: ^1.24.9
  teg_flutter_lints:
    git:
      url: git@github.com:transport-exchange-group/teg_flutter_lints
      ref: main


import_sorter:
  emojis: true
