name: flutter_import
description: Automatically organize your flutter imports
version: 0.0.1+4

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  args: ^2.4.2
  colorize: ^3.0.0
  yaml: ^3.1.2

dev_dependencies:
  test: ^1.24.9

import_sorter:
  emojis: true
